version: '3.9'
services:
  app:
    container_name: python_3
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    networks:
      - webnet

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    networks:
      - webnet      

networks:
  webnet: